apiVersion: v2
name: maintenance-operator
description: A Kubernetes operator that manages maintenance mode for Ingress and IngressRoute resources
type: application
version: 0.3.1
appVersion: "0.3.1"
keywords:
  - maintenance
  - operator
  - ingress
  - traefik
maintainers:
  - name: mithucste30
