{{- if .Values.clusterRole.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "maintenance-operator.fullname" . }}
  labels:
    {{- include "maintenance-operator.labels" . | nindent 4 }}
rules:
  # Ingress permissions
  - apiGroups: ["networking.k8s.io"]
    resources: ["ingresses"]
    verbs: ["get", "list", "watch", "patch", "update"]

  - apiGroups: ["networking.k8s.io"]
    resources: ["ingresses/status"]
    verbs: ["get", "patch", "update"]

  # IngressRoute (Traefik) permissions
  - apiGroups: ["traefik.io", "traefik.containo.us"]
    resources: ["ingressroutes"]
    verbs: ["get", "list", "watch", "patch", "update"]

  # ConfigMap permissions (for backups and maintenance page content)
  - apiGroups: [""]
    resources: ["configmaps"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]

  # Service permissions (to create maintenance services per namespace)
  - apiGroups: [""]
    resources: ["services"]
    verbs: ["get", "list", "create", "update", "patch", "delete"]

  # Pod permissions (to create maintenance pods per namespace)
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list", "create", "update", "patch", "delete"]

  # Events permissions (for logging)
  - apiGroups: [""]
    resources: ["events"]
    verbs: ["create", "patch"]

  # Kopf framework requirements
  - apiGroups: [""]
    resources: ["namespaces"]
    verbs: ["get", "list", "watch"]

  - apiGroups: ["apiextensions.k8s.io"]
    resources: ["customresourcedefinitions"]
    verbs: ["get", "list", "watch"]
{{- end }}
